//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 02:36:30 PM MST 
//


package org.cdsframework.util.table;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for query complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="query"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{org.cdsframework.util.table}tableName" minOccurs="0"/&gt;
 *         &lt;element ref="{org.cdsframework.util.table}queryClass"/&gt;
 *         &lt;element ref="{org.cdsframework.util.table}queryDml"/&gt;
 *         &lt;element ref="{org.cdsframework.util.table}rollbackOnNotFound" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "query", propOrder = {
    "tableName",
    "queryClass",
    "queryDml",
    "rollbackOnNotFound"
})
@XmlRootElement(name = "queryOperation")
public class QueryOperation
    implements Serializable
{

    private final static long serialVersionUID = -2458734520159483988L;
    protected String tableName;
    @XmlElement(required = true)
    protected String queryClass;
    @XmlElement(required = true)
    protected SelectElement queryDml;
    @XmlElement(defaultValue = "false")
    protected Boolean rollbackOnNotFound;

    /**
     * Gets the value of the tableName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * Sets the value of the tableName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTableName(String value) {
        this.tableName = value;
    }

    /**
     * Gets the value of the queryClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQueryClass() {
        return queryClass;
    }

    /**
     * Sets the value of the queryClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQueryClass(String value) {
        this.queryClass = value;
    }

    /**
     * Gets the value of the queryDml property.
     * 
     * @return
     *     possible object is
     *     {@link SelectElement }
     *     
     */
    public SelectElement getQueryDml() {
        return queryDml;
    }

    /**
     * Sets the value of the queryDml property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectElement }
     *     
     */
    public void setQueryDml(SelectElement value) {
        this.queryDml = value;
    }

    /**
     * Gets the value of the rollbackOnNotFound property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRollbackOnNotFound() {
        return rollbackOnNotFound;
    }

    /**
     * Sets the value of the rollbackOnNotFound property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRollbackOnNotFound(Boolean value) {
        this.rollbackOnNotFound = value;
    }

}
